apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-appoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-appoint
  template:
    metadata:
      labels:
        app: doctor-appoint
    spec:
      containers:
      - name: doctor-appoint
        image: thanishma/doctors-app
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-appoint
spec:
  type: NodePort
  selector:
    app: doctor-appoint
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000

    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doctor-ingress
spec:
  rules:
  - host: doctor.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: doctor-appoint
            port:
              number: 8000